# Generated by Django 4.2.1 on 2023-06-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('DEPT_NO', models.DecimalField(decimal_places=1, max_digits=3, primary_key=True, serialize=False)),
                ('DNAME', models.CharField(max_length=30)),
                ('LOC', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPNO', models.DecimalField(decimal_places=1, max_digits=5)),
                ('ENAME', models.CharField(max_length=50)),
                ('JOB', models.CharField(max_length=50)),
                ('MGR', models.DecimalField(decimal_places=1, max_digits=5)),
                ('HIRE_DATE', models.DateField()),
                ('SAL', models.DecimalField(decimal_places=2, max_digits=7)),
                ('COMM', models.DecimalField(decimal_places=1, max_digits=6)),
                ('DEPT_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
